buff's stuff @  2021-01-12	06:00:08	MST

diff --git a/buff-public/ia1/test/run b/buff-public/ia1/test/run
--- a/buff-public/ia1/test/run
+++ b/buff-public/ia1/test/run
@@ -20,5 +20,6 @@ for t in test-* ; do
     echo ${t##*/}
     [ -f $t/inp ] || > $t/inp
     eval java -cp .. Interpreter "$(Prgs $t/prg*)" < $t/inp > $t/out
-    cmp -s $t/exp $t/out || echo ${t##*/} failed >&2
+    diff -q -w $t/exp $t/out 2>/dev/null || echo ${t##*/} failed >&2
+    # cmp -s $t/exp $t/out || echo ${t##*/} failed >&2
 done
